name: riverpod_reg_example
description: Example usage of riverpod_reg
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  riverpod_reg:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

# Configuration for riverpod_reg
riverpod_reg:
  class_name: "AppProviders" # Optional, defaults to "MyProviders"
