targets:
  $default:
    builders:
      riverpod_reg:providers_file_builder:
        options:
          exclude:
            - "**/*.g.dart"
            - "**/*.freezed.dart"

builders:
  riverpod_reg_builder:
    import: "package:riverpod_reg/builder.dart"
    builder_factories: ["providersRegisterBuilder"]
    build_extensions:
      ".dart": [".riverpod_reg.part"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  providers_file_builder:
    import: "package:riverpod_reg/builder.dart"
    builder_factories: ["providersFileBuilder"]
    build_extensions:
      "$lib$": ["riverpod_reg.dart"]
    auto_apply: dependents
    build_to: source
