name: riverpod_reg
description: A code generator for Riverpod providers using build_runner
version: 1.0.0
homepage: https://github.com/lollipopkit/riverpod_reg

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  build: ^2.0.0
  build_runner: ^2.4.7
  glob: ^2.1.2
  meta: ^1.11.0
  riverpod_annotation: ^2.6.1
  source_gen: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0